### PR TITLE
[MRG] Unroll AggregateExceptions.

### LINKED ISSUE #170: Unroll AggregateExceptions
In some circumstances a user may run into AggregateException errors which are cryptic and unhelpful.

An AggregateException is an exception that is thrown from a separate thread and is a container for 1 or more actual exceptions that occurred on that thread.

Any occurrences of Aggregate Exception should be unrolled for the user so they can see the root exception messages.

### PR DESCRIPTION
**Pull request by chrispurnell**
Trying this again.

The AggregateException is throw from Task.WaitAll().
It only happend with threading is enabled an the --force option is not used.

Currently without --force when threading is disabled it stops after the first error.
But without --force when  threadding is enabled it waits until it has finished processing all the files and then if there was any exceptions along the way it skips the summary and shows the AggregateException message.

So my question is what should it do when you've not used the --force option, threadding is enabled and you get an exception?

### CODE REVIEW

**Comment by cmkushnir** [comment]
Not sure what force == true does, you explained force == false, threading == true|false.
Regardless, sounds like your question is force == false, threading == true, what to do on Exception;
however, you also said in this case it waits until all files processed and then throws AggregateException if there were any Exceptions.  Didn't you answer your own question ?  Or are you pondering if that's the correct approach ?

**Comment by chrispurnell** [comment]
```
  -f, --force               Skip files with errors and continue processing.
                            Do not pause for errors.
                            (Any errors will be written to MBINCompiler.log)
```
When force is true it will call ShowException() with wait=false when an exception occurs and then continue on.
It does much the same with and without threading enabled.

I said what it did do and asked what it should do.  I thought it would be clear that I was asking what the correct behavior is.
What is currently does without force and with threading is not useful.  Which would not be a problem if that wasn't the default.
I can only assume that it is supposed to behave much the same with and without threading.  But that is just an assumption and that is why I'm asking.

**Comment by chrispurnell** [comment]
This is the cleanest and simplest way I can think of to bring the theaded behavior in line with the unthreaded.
I'm going on the assumption here that what it does without threading is what is wanted.

Testing this I ran into another issue I have with the exception handling in MBINCompiler.
That is if it asked you if you want to overwrite a file and you say no it throws an exception.
I don't know about anyone else but I would expect it to just skip that file.

**Comment by chrispurnell** [comment]
I was hoping for some feedback.  The first two patches I think are good but I'm unhappy with the last because I used an exception to return an unexceptional state.  Alternatives are:

Use an out variable.
Test for the existence of the the file again after GetFileMode() returns to determine if ConvertFile() should return.
Test for the existence of the file in CovertFile() and pass it to GetFileMode().
Get rid of GerFileMode() and fold the code into ConvertFile().

**Comment by cmkushnir** [comment]
GetFileMode is private.  I usually consider private members and methods developers choice, as long as they work, since any future changes won't propagate beyond the class.

I don't understand the comment about only prompt user once, since it doesn't seem to save the choice anywhere.  I expected the comment to mean that if converting multiple files, and multiple already exist, only ask if they want to replace once and use that response for all existing files.

If you can simplify GetFileMode then I'd probably fold it into Convert.  If not then I'd likely do one of:
i) return a nullable FileMode
ii) return a tuple<bool, FileMode>
iii) return bool use out FileMode param e.g. bool TryGetFileMode( ... ), which mirrors other .NET API Try methods.
I would generally try to avoid testing if file exists twice.

**Comment by chrispurnell** [comment]
The comment about only prompt once appears to be trying to explain the need to synchronize.  Without the synchronization you could get multiple overwrite prompts before you have responded to the first one. You also need the full overwrite mode logic inside the synchronize block or you could get prompted again after requesting to always or never overwrite.

File: MBINCompiler/Source/Commands/Convert.cs [hunk 1]
```diff
@@ -310,22 +320,26 @@ private static void FileIsUnused(string filePath, MBINFile mbin)
         /// how to handle the file.
         /// </summary>
         /// <param name="file">The file path to check.</param>
-        /// <returns>A FileMode enum.</returns>
-        private static FileMode GetFileMode( string file ) {
+        /// <param name="fileMode">When the methord returns, contains the file mode.</param>
```
Comment (monkeyman192) [inline MBINCompiler/Source/Commands/Convert.cs]: typo ("methord")
Also, the wording is a bit unclear. Maybe "If set to true, the method returns the file mode."? (If my understanding is correct and this is what it does....)

Comment (chrispurnell) [reply MBINCompiler/Source/Commands/Convert.cs]: I was unsure about what how to describe the return value. For methods in this form the return value description always seems to be in the form of "true if <success>, otherwise false" where <success> is a description of what is considered a success. But in this case I have a specific failure condition. That being when the file exists and we don't want to overwrite it. When that happens the file mode is CreateNew and if you were to try and open the file with that file mode you would get an IOException.

**Comment by monkeyman192** [comment]
Ok, so just to be clear. If there are multiple files to overwrite and the user indicates that yes they want to overwrite them, it will overwrite all of them, it won't query per-file?
I think these changes look good, I just want to understand them! 😄

**Comment by chrispurnell** [comment]
This does not change the behaviour when the users indicates that they want to overwrite.  You've always had the four options: yes, no, overwrite all, keep all.  This does not change that.
What is does do is change what happens when the users says to not overwrite a file. Before it would throw some exceptions. It's included here because this PR is trying to fix some things about exception handling.

**Comment by monkeyman192** [comment]
Ok, Looks good I think then! I'll merge this change!
