### PR TITLE
[MRG] Calculate the alignment of classes at runtime.

### LINKED ISSUE #101: [INFO] Alignment Mechanism
So I have tried multiple times to fix alignment issues, and I think it is time to put this issue down once and for all.
I'm going to document what I believe is the way that alignment works, and then will implement it when I get time (hopefully this weekend). I think what we have currently is *pretty* close, but there are some small issues still persisting, and lot of the alignment code is quite ad-hoc or alignment is performed multiple times so the logic has become quite obscure.

There are two different methods of alignment. **Relative** alignment and **absolute** alignment.

**Relative alignment:**
*This applies to all fields within a struct.*
The alignment is relative to the start location of the current struct.

**Absolute alignment:**
*This applies to any struct that is in a list*
The alignment is relative to the start of the file.

In general we have the following alignment values:
Most structs align at *0x4* with a few exceptions:
 - booleans - none
 - strings - none
 - Vector4f's & Colours - 0x10
 - Most NMSTemplate objects - 0x8 [NOTE: this needs to be checked further...]
[Expection: structs that are only 0x4 long??]
 - List headers - 0x8

To ensure that the correct type of alignment is performed I think we need to add an extra argument to the (de)serializeValue function: `bool inlist`

We also need to ensure that the settings values are passed into the (de)serialization functions as the alignment of fields that are NMSTemplate's is an attribute of the struct, not the field.

I think most of these issues have been fixed, but it will be good to have a proper check over everything and make sure it is all working as intended and we can finally stop having to deal with stupid alignement issues (yay!!)

### PR DESCRIPTION
**Pull request by chrispurnell**
closes #101

### CODE REVIEW

**Comment by monkeyman192** [comment]
Looks good so far. My one main concern with this is one of performance. How much of a performance hit will there be with this when there is a large number of fields in a class and it's all recursive? I think one possible solution is to cache on each run, and also if you hit a field with alignment 0x10 automatically stop iterating over fields. Even with this I am not sure how much worse the performance will be...

**Comment by chrispurnell** [comment]
It is caching the alignment in the ConcurrentDictionary.

**Comment by chrispurnell** [comment]
Just done some speed tests.  Made a quick prog to calculate the alignments of all the template classes in a timed loop.
Using GetCustomAttribute() took about 0.014s.
Using GetAlignment() the first time took about 0.075s.
Using GetAlignment() after they've all been cached took less than 0.001s.

**Comment by chrispurnell** [comment]
Doing some more tests it seems that GetCustomAttribute() is faster the second time.
I was doing the GetCustomAttribute() loop after the GetAlignment() loop and GetAlignment() calls GetCustomAttribute().
From cold GetCustomAttribute() took 0.025s.
And  GetAlignment() took 0.064s after doing just the GetCustomAttribute() loop.

**Comment by cmkushnir** [comment]
In GetAlignment suggest changing:
if (type.BaseType == typeof(NMSTemplate))
to
if( type.IsSubclassOf(typeof(NMSTemplate)) )
to allow classes that don't have NMSTemplate as their immediate base.

e.g. planned changes to INMSString would have INMSString derive from NMSTemplate and NMSString* derive from INMSString.

Would suggest this change throughout the code.  Just need to remember that IsSubclassOf returns false if types are equal.  Not an issue in GetAlignment since you have a prior case to handle type == NMSTemplate.

**Comment by chrispurnell** [comment]
It would need to be consistant throughout the code.

**Comment by chrispurnell** [comment]
I've finished all my testing.
Everything looks good.
Alignment issues seem fixed.
Perfomance looks good thanks to the caching working.

You do get a situation where at the start of a mbin decompile all the threads want the alignment of MBINHeader all at once.
They want the alignment of that class due to the code I added to realign at the end of any class to avoid the need for end padding.
Since at that point it has not been cached they all iterate over the fields.
It might be an idea to add an alignment attribute there.  But what to set it to?

If no one has any objections I'll be changing the tag in the title.

**Comment by HolterPhylo** [comment]
Noob here, why not pre-get the alignment of MBINHeader before the threads start a mbin decompile and feed that to all those threads looking for it.  I am sure I am missing something here!

**Comment by chrispurnell** [comment]
Because that would be a compex solution to a trivial non issue.

**Comment by HolterPhylo** [comment]
I see, thanks
I just only understand half of all you guys are talking about, but learning a lot!

File: libMBIN/Source/Template/NMSTemplate.cs [hunk 1]
```diff
@@ -208,8 +282,7 @@ public class NMSTemplate
                         }
                         return array;
                     } else {
-                        int alignment = field.GetCustomAttribute<NMSAttribute>()?.Alignment ?? 0x4;
-                        reader.Align( alignment ); // templatePosition when not in list??
+                        reader.Align( GetAlignment(field) ); // templatePosition when not in list??
```
Comment (monkeyman192) [inline libMBIN/Source/Template/NMSTemplate.cs]: I think this comment (and the same one later can be removed...)

File: libMBIN/Source/Template/NMSTemplate.cs [hunk 2]
```diff
@@ -109,6 +110,79 @@ public class NMSTemplate
...
+                    }
+
+                    if (type.BaseType == typeof(NMSTemplate))
+                    {
+                        alignment = 1;
+
+                        foreach (FieldInfo field in type.GetFields())
+                        {
+                            int align = GetAlignment(field.FieldType);
+                            if (align > alignment) alignment = align;
```
Comment (monkeyman192) [inline libMBIN/Source/Template/NMSTemplate.cs]: I think add the `if (alignment == 0x10) break` so that once it hits the maximum alignment it stops? To add a little more efficiency?

Comment (chrispurnell) [reply libMBIN/Source/Template/NMSTemplate.cs]: I didn't think this would do much as the vast majority of classes have an alignment of 8 and most of the rest have an alignment of 4.
I did a speed test and in the calculate the alignment of everything test it did shave about 0.003 seconds off the time.

**Comment by monkeyman192** [comment]
> 
> 
> I've finished all my testing.
> Everything looks good.
> Alignment issues seem fixed.
> Perfomance looks good thanks to the caching working.
> 
> You do get a situation where at the start of a mbin decompile all the threads want the alignment of MBINHeader all at once.
> They want the alignment of that class due to the code I added to realign at the end of any class to avoid the need for end padding.
> Since at that point it has not been cached they all iterate over the fields.
> It might be an idea to add an alignment attribute there. But what to set it to?
> 
> If no one has any objections I'll be changing the tag in the title.

I'm not sure if I fully understand the issue here? The header will always have 0x60 bytes written, so I think you can probably just give it an alignment of anything, but maybe 0x8 or 0x4 would be suitable. In reality I think it actually doesn't matter...
I always forget that the header is subclassed from NMSTemplate... 😅

I really like the use of a ConcurrentDictionary! This way we get the speedup across threads (right?) which I think is really neat!
Looks really good! 🥇 
Edit: Would you be able to give some details on the seed tests you ran? What was the same size you ran it on etc etc?

File: libMBIN/Source/Template/NMSTemplate.cs (hunk 2 above)
Comment (cmkushnir) [reply libMBIN/Source/Template/NMSTemplate.cs]: Strictly speaking the enum test should use the alignment of the UnderlyingType, not just assume 4.
Would set initial dict capacity to 2003 (prime > # of expected entries) to minimize internal resizing while adding and chance of hash collisions.
To optimize for speed would still suggest starting the method with a switch on Type.GetTypeCode(type) to handle pod types, use return instead of break in the pod cases (don't cache).  This would be faster than a concurrent dict lookup and put less load on the dict locks (less chance of blocking and incurring thread context switch).  It would also handle the enum case correctly for free.

**Comment by chrispurnell** [comment]
This issuse with the alignment of the header is that it's alignment does not matter becuase it is size 0x60 and always placed at file position 0x0.  It contains fields of alignment 0x8 but can also be placed before an object of alignment 0x10.

The ConcurrentDictionary is stored in a global variable (static field) that persists for the lifetime of the program and is visible across threads.  Which is why I needed to use a thread safe container.  Becuse there is no locking outside the ConcurrentDictionary the alignment of any type can be calculated up to once per running thread.

I only mentioned MBINHeader because it was notable as being the only type whos alignment got calculated as many times as I have CPU threads.  I tested this by adding a log statement at the end of GetAlignment() and running MBINCompiler on all the game's MBINs.

For the speed test I created a small test program that looped over a list of all the template class types and called GetAlignment() for each of them.  I stored the result in an array to do something with later because I've had problems in the past of JIT compilers optimizing away do nothing benchmarks.  And I timed the loop with a System.Diagnostics.Stopwatch object.

**Comment by chrispurnell** [comment]
Just force pushed a rebase.

**Comment by monkeyman192** [comment]
out of curiosity, does this fix #232 ??

**Comment by chrispurnell** [comment]
I think #232 has been fixed since PR #319.
